{{- if .Values.puppetserver.puppeturl }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: r10k-code-config
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
data:
  r10k.yaml: |
    # The location to use for storing cached Git repos
    :cachedir: '/etc/puppetlabs/code/r10k_cache'
    # A list of git repositories to create
    :sources:
      # This will clone the git repository and instantiate an environment per
      # branch in '/etc/puppetlabs/code/environments'
      :puppet_repo:
        remote: '{{.Values.puppetserver.puppeturl}}'
        basedir: '/etc/puppetlabs/code/environments'

  r10k_code_cronjob.sh: |
    #!/usr/bin/env sh
    {{- if .Values.r10k.code.cronJob.concurrencyPolicy }}
      {{- if eq .Values.r10k.code.cronJob.concurrencyPolicy "Forbid" }}
        if [ -e ~/.r10k_cronjob.pid ] && pgrep $(<~/.r10k_cronjob.pid); then
          exit 0
        fi
      {{- else if eq .Values.r10k.code.cronJob.concurrencyPolicy "Replace" }}
        if [ -e ~/.r10k_cronjob.pid ]; then
          pkill $(<~/.r10k_cronjob.pid)
        fi
      {{- end }}
    {{- end }}
    # extra_args="{{ .Values.r10k.code.extraArgs }}"  # parsing yaml-maps to bash?
    echo $PPID > ~/.r10k_cronjob.pid
    /docker-entrypoint.sh deploy environment --config /etc/puppetlabs/puppet/r10k.yaml --puppetfile > ~/.r10k_code_cronjob.out 2>&1
    retVal=$?
    if [ "$retVal" -eq "0" ]; then
      touch ~/.r10k_code_cronjob.success > /dev/null 2>&1
    else
      rm ~/.r10k_code_cronjob.success > /dev/null 2>&1
    fi
    rm ~/.r10k_cronjob.pid
    exit $retVal

  r10k_code_entrypoint.sh: |
    #!/usr/bin/env sh
    cat > ~/.r10k_code_crontab <<'EOF'
    {{ .Values.r10k.code.cronJob.schedule }} /bin/sh -c /etc/puppetlabs/puppet/r10k_code_cronjob.sh
    EOF
    tail -F ~/.r10k_code_cronjob.out &
    supercronic -json ~/.r10k_code_crontab
{{- end }}
