{{- if .Values.hiera.hieradataurl }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: r10k-hiera-config
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
data:
  r10k.yaml: |
    # The location to use for storing cached Git repos
    :cachedir: '/etc/puppetlabs/code/r10k_cache'
    # A list of git repositories to create
    :sources:
      # This will clone the git repository and instantiate an environment per
      # branch in '/etc/puppetlabs/code/hiera-data'
      :hiera_repo:
        remote: '{{.Values.hiera.hieradataurl}}'
        basedir: '/etc/puppetlabs/code/hiera-data'

  r10k_hiera_cronjob.sh: |
    #!/usr/bin/env sh
    # not needed anymore, as crond handels this - .startingDeadlineSeconds: {{ .startingDeadlineSeconds }}
    # not needed anymore, as crond handels this - .activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
    {{- if .Values.r10k.hiera.cronJob.concurrencyPolicy }}
      {{- if eq .Values.r10k.hiera.cronJob.concurrencyPolicy "Forbid" }}
        if [ -e ~/.r10k_cronjob.pid ] && pgrep $(<~/.r10k_cronjob.pid); then
          exit 0
        fi
      {{- else if eq .Values.r10k.hiera.cronJob.concurrencyPolicy "Replace" }}
        if [ -e ~/.r10k_cronjob.pid ]; then
          pkill $(<~/.r10k_cronjob.pid)
        fi
      {{- end }}
    {{- end }}
    # extra_args="{{ .Values.r10k.hiera.extraArgs }}"  # parsing yaml-maps to bash?
    echo $PPID > ~/.r10k_cronjob.pid
    /docker-entrypoint.sh deploy environment --config /etc/puppetlabs/puppet/r10k.yaml --puppetfile > ~/.r10k_hiera_cronjob.out 2>&1
    retVal=$?
    if [ "$retVal" -e "0" ]; then
      touch ~/.r10k_hiera_cronjob.success
    else
      rm ~/.r10k_hiera_cronjob.success
    fi
    rm ~/.r10k_cronjob.pid
    exit $retVal

  r10k_hiera_entrypoint.sh: |
    #!/usr/bin/env sh
    cat > ~/.r10k_hiera_crontab <<'EOF'
    {{ .Values.r10k.hiera.cronJob.schedule }} /bin/sh -c /etc/puppetlabs/puppet/r10k_hiera_cronjob.sh
    EOF
    tail -F ~/.r10k_hiera_cronjob.out &
    supercronic -json ~/.r10k_hiera_crontab
{{- end }}
